---
apiVersion: projectcalico.org/v3
kind: GlobalThreatFeed
metadata:
  name: snort.ipthreatfeeds
spec:
  pull:
    http:
      url: https://snort.org/downloads/ip-block-list
  globalNetworkSet:
    labels:
      feed: snort-ipthreatfeed
