wordpressUsername: admin
wordpressPassword: mcd0n@lds!!
persistence:
  enabled: false

mariadb:
  auth:
    rootPassword: mcd0n@lds!!
  primary:
    persistence:
      enabled: false

service:
  nodePorts:
    http: 30080
    https: 30443
